### ISSUE TITLE
Pairwise distances

### ISSUE THREAD

**Issue by jorisvandenbossche** [martinfleis/efficient-geopandas-workshop#1]
Writing up here, and with some questions (can push when I am sure you are not doing that to avoid conflicts in the notebook)

### Pairwise distances

> **QUESTION:** How to calculate the distance between all points of two GeoDataFrames?

```
points1 = geopandas.points_from_xy(numpy.random.uniform(0, 1000, 1_000), numpy.random.uniform(0, 1000, 1_000))
gdf1 = geopandas.GeoDataFrame(geometry=points1)
points2 = geopandas.points_from_xy(numpy.random.uniform(0, 1000, 1_000), numpy.random.uniform(0, 1000, 1_000))
gdf2 = geopandas.GeoDataFrame(geometry=points2)
```

(can maybe just use one dataframe and do pairwise with itself to simplify)

```
%%time
# do not use this code
gdf1.geometry.apply(lambda g: gdf2.distance(g))
```
-> ca 750ms

We can use the broadcasting of the shapely ufunc by reshaping as 2D arrays (a (N, 1) and (1, N) gives (N, N) result): 

```
%%time
shapely.distance(np.asarray(gdf1.geometry)[:, np.newaxis], np.asarray(gdf2.geometry)[np.newaxis, :])
```
-> ca 500ms

Note: so this doesn't give that much of a speedup nowadays, since both are using the fast ufunc under the hood, and distance is a relatively expensive function, and so you are only avoiding the inner loop for one dimension. 

So it's not that big of an improvement.

I was think that we could show as a follow-up to use an strtree: what if you only want the distances for points that are less than xx m away from each other?

```
tree = shapely.STRtree(gdf1.geometry)
```
```
%%time
idx2, idx1 = tree.query(gdf2.geometry, predicate="dwithin", distance=100)
shapely.distance(np.asarray(gdf1.geometry)[idx1], np.asarray(gdf2.geometry)[idx2])
```
-> ca 80ms

We can't directly use `query_nearest` here, unless you of course are fine with just getting the one nearest within a search radius, instead of all within a search radius. 

I suppose we will already show nearest as well in another example, or can combine it with this one?

**Comment by martinfleis** [comment]
> So it's not that big of an improvement.

Would we consider using shapely as a recommended pattern over apply? I see roughly 10% difference on my laptop.

> I was think that we could show as a follow-up to use an strtree: what if you only want the distances for points that are less than xx m away from each other?

I like that. And yes, it can be done with nearest (it is on the list but I haven't done the actual code).

> can push when I am sure you are not doing that to avoid conflicts in the notebook

I am not touching it now. Will wait for a signal to do that again :).

**Comment by jorisvandenbossche** [comment]
> > So it's not that big of an improvement.
> 
> Would we consider using shapely as a recommended pattern over apply? I see roughly 10% difference on my laptop.

Maybe we can still show it, and we can explain why it's not much of a difference. But eg also memory-wise the shapely version should be a bit better, as that creates the resulting array in one go, while the pandas apply version gets an array for each row and then concatenates them into a single 2D array

**Comment by martinfleis** [comment]
Fine with me.

**Comment by jorisvandenbossche** [comment]
Done in https://github.com/martinfleis/efficient-geopandas-workshop/pull/3
